const HTTP_OK_STATUS = 200;

const HTTP_BAD_REQUEST_STATUS = 400;
const HTTP_NOT_FOUND_STATUS = 404;

const HTTP_INTERNAL_SERVER_ERROR = 500;

module.exports = {
HTTP_OK_STATUS,
HTTP_BAD_REQUEST_STATUS,
HTTP_NOT_FOUND_STATUS,
HTTP_INTERNAL_SERVER_ERROR,
};